using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;                                   //UI에 접근하기 위해서 사용


public class Player
{
    private int hp = 100;                               //hp 를 선언한 후 100의 값을 입력
    private int Power = 50;                             //power를 선언한 후 50의 값을 입력

    public void Attack()    
    {
        Debug.Log(this.Power + " 데미지를 입혔다.");   //this는 Player 클래스를 이야기한다.
    }

    public void Damage(int damage)                     //Damage 함수는 int 형태로 받은 데미지 인수를 받는다.
    {
        this.hp -= damage;
        Debug.Log(damage + " 데미지를 입혔다.");
    }

    public int GetHp()                                 //private 로 선언되어있는 Hp 변수 값을 함수로 통해서 전달
    {
        return this.hp;
    }
}

public class Test_008 : MonoBehaviour
{
    Player player_01 = new Player();
    Player player_02 = new Player();
    public Text player01HP;
    public Text player02HP;

    // Start is called before the first frame update
    void Start()
    {
        Player player_01 = new Player();                //위에 만든 플레이어 클래스를 선언한다.
        player_01.Attack();                             //생성한 player_01 의 Attack 함수를 실행시킨다.
        player_01.Damage(30);                           //생성한 player_01 의 Damage 함수를 실행시킨다.
    }

    // Update is called once per frame
    void Update()
    {
        player01HP.text = "Player 01 HP : " + player_01.GetHp().ToString();             //GetHp() 함수를 호출하고 ToStering으로 문자열로 변환
        player02HP.text = "Player 02 HP : " + player_02.GetHp().ToString();             //GetHp() 함수를 호출하고 ToStering으로 문자열로 변환

        if (Input.GetMouseButtonDown(0))                //왼쪽 마우스를 눌렸을 때
        {
            player_01.Damage(1);                        //player_01의 객체의 함수 Damage를 실행 (피라미터로는 1을 넣음)
        }

        if (Input.GetMouseButtonDown(1))                //오른쪽 마우스를 눌렸을 때
        {
            player_02.Damage(1);                        //player_01의 객체의 함수 Damage를 실행 (피라미터로는 1을 넣음)
        }

    }
}
